/**
 * ============================================================
 *  QAMASHI YOSHLAR PORTALI — Backend Server
 *  Stack: Node.js + Express + SQLite + JWT
 *  Author: Generated by Claude (Anthropic)
 * ============================================================
 */

"use strict";

const express    = require("express");
const sqlite3    = require("sqlite3").verbose();
const jwt        = require("jsonwebtoken");
const cors       = require("cors");
const bodyParser = require("body-parser");
const path       = require("path");

// ─── Configuration ────────────────────────────────────────────────────────────
const PORT          = process.env.PORT || 3001;
const ADMIN_PASS    = process.env.ADMIN_PASS || "2026";
const JWT_SECRET    = process.env.JWT_SECRET || "qamashi_secret_2026_portal_key";
const JWT_EXPIRES   = "8h";           // Token valid for 8 hours
const DB_PATH       = path.join(__dirname, "portal.db");

// ─── App Init ─────────────────────────────────────────────────────────────────
const app = express();

// ─── Middleware ───────────────────────────────────────────────────────────────
app.use(cors({
  origin: "*",
  methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
  allowedHeaders: ["Content-Type", "Authorization"]
}));

// Increase limit for Base64 images (up to 10 MB)
app.use(bodyParser.json({ limit: "10mb" }));
app.use(bodyParser.urlencoded({ extended: true, limit: "10mb" }));

// Serve the frontend from the same directory (optional convenience)
app.use(express.static(path.join(__dirname)));

// ─── SQLite Database ──────────────────────────────────────────────────────────
const db = new sqlite3.Database(DB_PATH, (err) => {
  if (err) {
    console.error("❌  Could not open database:", err.message);
    process.exit(1);
  }
  console.log(`✅  Connected to SQLite database at ${DB_PATH}`);
});

// Enable WAL mode for better concurrent read performance
db.run("PRAGMA journal_mode=WAL");

// Create the news table if it doesn't exist
db.run(`
  CREATE TABLE IF NOT EXISTS news (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    title_uz    TEXT    NOT NULL DEFAULT '',
    title_ru    TEXT    NOT NULL DEFAULT '',
    title_en    TEXT    NOT NULL DEFAULT '',
    desc_uz     TEXT    NOT NULL DEFAULT '',
    desc_ru     TEXT    NOT NULL DEFAULT '',
    desc_en     TEXT    NOT NULL DEFAULT '',
    date        TEXT    NOT NULL,
    image       TEXT    DEFAULT NULL,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
  )
`, (err) => {
  if (err) {
    console.error("❌  Could not create table:", err.message);
  } else {
    console.log("✅  News table ready.");
    // Seed with sample data if the table is empty
    seedIfEmpty();
  }
});

// ─── Seed Data ────────────────────────────────────────────────────────────────
function seedIfEmpty() {
  db.get("SELECT COUNT(*) as count FROM news", (err, row) => {
    if (err || row.count > 0) return;

    const samples = [
      {
        title_uz: "Qamashi yoshlari uchun stipendiya dasturi",
        title_ru: "Программа стипендий для молодёжи Камаши",
        title_en: "Scholarship Program for Qamashi Youth",
        desc_uz:  "Qamashi tumanida istiqbolli yoshlarga yangi stipendiya dasturi ishga tushirildi. Dastur doirasida 50 nafar talabaga moliyaviy yordam ko'rsatiladi.",
        desc_ru:  "В Камашинском районе запущена новая программа стипендий для перспективной молодёжи. В рамках программы финансовая поддержка будет оказана 50 студентам.",
        desc_en:  "A new scholarship program for promising youth has been launched in Qamashi district. 50 students will receive financial support under the program.",
        date:     "2025-04-15",
        image:    null
      },
      {
        title_uz: "Yoshlar kuni: bayram tadbirlari",
        title_ru: "День молодёжи: праздничные мероприятия",
        title_en: "Youth Day: Festive Events",
        desc_uz:  "Qamashi markaziy maydonida yoshlar kuni munosabati bilan katta bayram tadbiri bo'lib o'tdi. 500 dan ortiq yoshlar ishtirok etdi.",
        desc_ru:  "На центральной площади Камаши прошёл большой праздник по случаю Дня молодёжи. В нём приняли участие более 500 молодых людей.",
        desc_en:  "A grand celebration was held at Qamashi central square on the occasion of Youth Day. Over 500 young people participated.",
        date:     "2025-06-25",
        image:    null
      },
      {
        title_uz: "IT-ko'nikmalar bo'yicha bepul kurslar",
        title_ru: "Бесплатные курсы по IT-навыкам",
        title_en: "Free IT Skills Courses",
        desc_uz:  "Qamashi yoshlar markazida bepul IT kurslari ro'yxatga olish boshlandi. Dasturlash, dizayn va raqamli marketing yo'nalishlarida ta'lim beriladi.",
        desc_ru:  "В молодёжном центре Камаши открылась регистрация на бесплатные IT-курсы. Обучение по направлениям: программирование, дизайн и digital-маркетинг.",
        desc_en:  "Registration for free IT courses has opened at the Qamashi Youth Center. Training in programming, design, and digital marketing is offered.",
        date:     "2025-09-01",
        image:    null
      }
    ];

    const stmt = db.prepare(`
      INSERT INTO news (title_uz, title_ru, title_en, desc_uz, desc_ru, desc_en, date, image)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `);

    samples.forEach((s) => {
      stmt.run(s.title_uz, s.title_ru, s.title_en, s.desc_uz, s.desc_ru, s.desc_en, s.date, s.image);
    });

    stmt.finalize();
    console.log("🌱  Seeded 3 sample news items.");
  });
}

// ─── JWT Middleware ───────────────────────────────────────────────────────────
/**
 * Verifies the JWT token in the Authorization header.
 * Attaches `req.admin = true` if valid.
 */
function requireAuth(req, res, next) {
  const authHeader = req.headers["authorization"];
  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return res.status(401).json({ success: false, message: "Unauthorized: No token provided." });
  }

  const token = authHeader.split(" ")[1];
  jwt.verify(token, JWT_SECRET, (err, decoded) => {
    if (err) {
      return res.status(403).json({ success: false, message: "Forbidden: Invalid or expired token." });
    }
    req.admin = decoded.admin;
    next();
  });
}

// ─── Helper: Wrap db.all / db.run in Promises ─────────────────────────────────
const dbAll = (sql, params = []) =>
  new Promise((resolve, reject) =>
    db.all(sql, params, (err, rows) => (err ? reject(err) : resolve(rows)))
  );

const dbRun = (sql, params = []) =>
  new Promise((resolve, reject) =>
    db.run(sql, params, function (err) {
      if (err) reject(err);
      else resolve({ lastID: this.lastID, changes: this.changes });
    })
  );

const dbGet = (sql, params = []) =>
  new Promise((resolve, reject) =>
    db.get(sql, params, (err, row) => (err ? reject(err) : resolve(row)))
  );

// ─── Routes ───────────────────────────────────────────────────────────────────

/**
 * POST /api/login
 * Body: { password: string }
 * Returns: { success, token, message }
 */
app.post("/api/login", (req, res) => {
  const { password } = req.body;

  if (!password) {
    return res.status(400).json({ success: false, message: "Password is required." });
  }

  if (password !== ADMIN_PASS) {
    // Intentionally vague error for security
    return res.status(401).json({ success: false, message: "Invalid credentials." });
  }

  const token = jwt.sign(
    { admin: true, iat: Math.floor(Date.now() / 1000) },
    JWT_SECRET,
    { expiresIn: JWT_EXPIRES }
  );

  return res.json({
    success: true,
    token,
    message: "Login successful."
  });
});

/**
 * GET /api/news
 * Returns all news, newest first.
 */
app.get("/api/news", async (req, res) => {
  try {
    const rows = await dbAll("SELECT * FROM news ORDER BY date DESC, created_at DESC");
    return res.json({ success: true, data: rows });
  } catch (err) {
    console.error("GET /api/news error:", err);
    return res.status(500).json({ success: false, message: "Database error." });
  }
});

/**
 * GET /api/news/:id
 * Returns a single news item by ID.
 */
app.get("/api/news/:id", async (req, res) => {
  const { id } = req.params;
  try {
    const row = await dbGet("SELECT * FROM news WHERE id = ?", [id]);
    if (!row) return res.status(404).json({ success: false, message: "News not found." });
    return res.json({ success: true, data: row });
  } catch (err) {
    console.error("GET /api/news/:id error:", err);
    return res.status(500).json({ success: false, message: "Database error." });
  }
});

/**
 * POST /api/news (Protected)
 * Body: { title_uz, title_ru, title_en, desc_uz, desc_ru, desc_en, date, image? }
 */
app.post("/api/news", requireAuth, async (req, res) => {
  const { title_uz, title_ru, title_en, desc_uz, desc_ru, desc_en, date, image } = req.body;

  // Basic validation
  if (!title_uz && !title_en && !title_ru) {
    return res.status(400).json({ success: false, message: "At least one title is required." });
  }
  if (!date) {
    return res.status(400).json({ success: false, message: "Date is required." });
  }

  try {
    const result = await dbRun(
      `INSERT INTO news (title_uz, title_ru, title_en, desc_uz, desc_ru, desc_en, date, image)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      [title_uz || "", title_ru || "", title_en || "", desc_uz || "", desc_ru || "", desc_en || "", date, image || null]
    );
    const newRow = await dbGet("SELECT * FROM news WHERE id = ?", [result.lastID]);
    return res.status(201).json({ success: true, data: newRow, message: "News created successfully." });
  } catch (err) {
    console.error("POST /api/news error:", err);
    return res.status(500).json({ success: false, message: "Database error." });
  }
});

/**
 * PUT /api/news/:id (Protected)
 * Body: partial news fields to update
 */
app.put("/api/news/:id", requireAuth, async (req, res) => {
  const { id } = req.params;
  const { title_uz, title_ru, title_en, desc_uz, desc_ru, desc_en, date, image } = req.body;

  try {
    const existing = await dbGet("SELECT * FROM news WHERE id = ?", [id]);
    if (!existing) return res.status(404).json({ success: false, message: "News not found." });

    const updated = {
      title_uz: title_uz ?? existing.title_uz,
      title_ru: title_ru ?? existing.title_ru,
      title_en: title_en ?? existing.title_en,
      desc_uz:  desc_uz  ?? existing.desc_uz,
      desc_ru:  desc_ru  ?? existing.desc_ru,
      desc_en:  desc_en  ?? existing.desc_en,
      date:     date     ?? existing.date,
      image:    image !== undefined ? image : existing.image
    };

    await dbRun(
      `UPDATE news SET
        title_uz = ?, title_ru = ?, title_en = ?,
        desc_uz  = ?, desc_ru  = ?, desc_en  = ?,
        date = ?, image = ?
       WHERE id = ?`,
      [updated.title_uz, updated.title_ru, updated.title_en,
       updated.desc_uz,  updated.desc_ru,  updated.desc_en,
       updated.date, updated.image, id]
    );

    const newRow = await dbGet("SELECT * FROM news WHERE id = ?", [id]);
    return res.json({ success: true, data: newRow, message: "News updated successfully." });
  } catch (err) {
    console.error("PUT /api/news/:id error:", err);
    return res.status(500).json({ success: false, message: "Database error." });
  }
});

/**
 * DELETE /api/news/:id (Protected)
 */
app.delete("/api/news/:id", requireAuth, async (req, res) => {
  const { id } = req.params;
  try {
    const existing = await dbGet("SELECT id FROM news WHERE id = ?", [id]);
    if (!existing) return res.status(404).json({ success: false, message: "News not found." });

    await dbRun("DELETE FROM news WHERE id = ?", [id]);
    return res.json({ success: true, message: `News #${id} deleted successfully.` });
  } catch (err) {
    console.error("DELETE /api/news/:id error:", err);
    return res.status(500).json({ success: false, message: "Database error." });
  }
});

// ─── 404 Handler ──────────────────────────────────────────────────────────────
app.use((req, res) => {
  res.status(404).json({ success: false, message: "Endpoint not found." });
});

// ─── Global Error Handler ─────────────────────────────────────────────────────
app.use((err, req, res, next) => {
  console.error("Unhandled error:", err);
  res.status(500).json({ success: false, message: "Internal server error." });
});

// ─── Start Server ─────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`
  ╔═══════════════════════════════════════════════╗
  ║       QAMASHI YOSHLAR PORTALI — BACKEND       ║
  ║  Server running at  http://localhost:${PORT}     ║
  ║  Admin password: ${ADMIN_PASS}                         ║
  ╚═══════════════════════════════════════════════╝
  `);
});

// ─── Graceful Shutdown ────────────────────────────────────────────────────────
process.on("SIGINT", () => {
  db.close((err) => {
    if (err) console.error("Error closing DB:", err.message);
    else console.log("\n🔒  Database connection closed. Bye!");
    process.exit(0);
  });
});
